[package]
name = "prism"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "prism"
path = "src/main.rs"

[dependencies]
prism_engine = { workspace = true }
prism_chess = { workspace = true }

[build-dependencies]
chrono = "0.4"

[features]
tunable = ["prism_engine/tunable"]
debug = ["prism_engine/debug"]
release = []