[package]
name = "valkyrie"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "valkyrie"
path = "src/main.rs"

[dependencies]
valkyrie_engine = { workspace = true }
valkyrie_chess = { workspace = true }

[build-dependencies]
chrono = "0.4"

[features]
tunable = ["valkyrie_engine/tunable"]
debug = ["valkyrie_engine/debug"]
release = []