[package]
name = "prism_engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lib]
name = "prism_engine"
crate-type = ["lib"]

[dependencies]
prism_chess = { workspace = true }

[features]
tunable = []